# Use the OpenJDK 23 image as the base image
#FROM maven:3.6.0-jdk-11-slim AS build
#COPY src /home/app/src
#COPY pom.xml /home/app
#RUN mvn -f /home/app/pom.xml clean package \

#FROM openjdk:23
#
#WORKDIR /app
#COPY .mvn .mvn
#COPY mvnw mvnw.cmd pom.xml ./
#COPY src ./src
#RUN chmod +x mvnw.cmd
#CMD ["mvnw", "install"]